insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (1, 248, 'Joanna Nowak', true, 'Tajemnice zamku', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (2, 235, 'Jan Kowalski', true, 'Czerwona zagadka', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (3, 250, 'Anna Wojciechowska', true, 'Podróże w czasie', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (5, 195, 'Andrzej Kaczor', true, 'Światło i cień', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (6, 264, 'Agnieszka Słowik', true, 'Szczęśliwe wspomnienia', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (7, 272, 'Dawid Jankowski', true, 'Wyścig z czasem', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (8, 228, 'Marek Pawłowski', true, 'Droga do szczęścia', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (9, 297, 'Jakub Majewski', true, 'Przygody w świecie fantasy', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (10, 236, 'Katarzyna Nowak', true, 'Zaginiony skarb', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (11, 278, 'Piotr Wiśniewski', true, 'Złodzieje czasu', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (12, 247, 'Kamil Kaczmarek', true, 'Czas zemsty', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (13, 212, 'Monika Nowicka', true, 'Myszka w krainie zwierząt', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (14, 235, 'Krystyna Kowalska', true, 'Dziewczynka z zapałkami', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (15, 250, 'Kamila Górska', true, 'Bajka o złodzieju', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (16, 239, 'Rafał Nowicki', true, 'Szalone wakacje', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (17, 211, 'Krzysztof Nowakowski', true, 'Niesamowite przygody', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (18, 287, 'Marta Słowik', true, 'Zamieszki na stadionie', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (19, 209, 'Kamil Kaczor', true, 'Odwaga i honor', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (20, 219, 'Piotr Majewski', true, 'Podróż w czasie', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (21, 256, 'Katarzyna Wiśniewska', true, 'Świat w obiektywie', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (22, 283, 'Dariusz Jankowski', true, 'Tajemnice zamku', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (23, 210, 'Łukasz Kowalczyk', true, 'Księga mocy', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (24, 234, 'Aneta Nowicka', true, 'Czas zemsty', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (25, 296, 'Mirosław Wojciechowski', true, 'Czerwona zagadka', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (26, 256, 'Krzysztof Kaczmarek', true, 'Zaginiony skarb', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (27, 249, 'Weronika Górska', true, 'Szczęśliwe wspomnienia', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (28, 220, 'Kamil Pawłowski', true, 'Bajka o złodzieju', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (29, 296, 'Jakub Wiśniewski', true, 'Złodzieje czasu', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (30, 288, 'Jan Kaczor', true, 'Myszka w krainie zwierząt', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (31, 286, 'Krzysztof Słowik', true, 'Dziewczynka z zapałkami', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (32, 297, 'Piotr Kowalski', true, 'Szalone wakacje', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (33, 250, 'Katarzyna Nowicka', true, 'Światło i cień', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (34, 269, 'Aneta Majewska', true, 'Niesamowite przygody', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (35, 212, 'Jan Nowakowski', true, 'Zamieszki na stadionie', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (36, 269, 'Kamil Wiśniewska', true, 'Podróż w czasie', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (37, 221, 'Anna Kaczmarek', true, 'Księga mocy', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (38, 239, 'Kamil Jankowski', true, 'Odwaga i honor', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (39, 280, 'Monika Kowalczyk', true, 'Przygody w świecie fantasy', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (40, 265, 'Łukasz Nowak', true, 'Tajemnice zamku', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (41, 228, 'Krzysztof Górski', true, 'Czerwona zagadka', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (42, 202, 'Kamil Wojciechowski', true, 'Podróże w czasie', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (43, 295, 'Agnieszka Pawłowska', true, 'Świat w obiektywie', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (44, 253, 'Mirosław Nowakowski', true, 'Światło i cień', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (45, 225, 'Jan Słowik', true, 'Szczęśliwe wspomnienia', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (46, 284, 'Krystyna Jankowska', true, 'Szalone wakacje', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (47, 286, 'Katarzyna Majewski', true, 'Zamieszki na stadionie', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (48, 245, 'Kamil Kowalski', true, 'Bajka o złodzieju', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (49, 266, 'Dawid Kaczor', true, 'Złodzieje czasu', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (50, 250, 'Agnieszka Wiśniewski', true, 'Myszka w krainie zwierząt', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (51, 212, 'Kamila Nowicka', true, 'Dziewczynka z zapałkami', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (52, 212, 'Aneta Wiśniewska', true, 'Księga mocy', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (53, 251, 'Krzysztof Kowalczyk', true, 'Odwaga i honor', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (54, 290, 'Kamil Nowakowski', true, 'Przygody w świecie fantasy', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (55, 218, 'Marta Kaczmarek', true, 'Czas zemsty', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (56, 252, 'Rafał Górski', true, 'Zaginiony skarb', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (57, 201, 'Weronika Pawłowski', true, 'Szczęśliwe wspomnienia', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (58, 258, 'Dariusz Nowak', true, 'Bajka o złodzieju', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (59, 227, 'Kamila Majewska', true, 'Szalone wakacje', 2014);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (60, 219, 'Andrzej Wiśniewska', true, 'Zamieszki na stadionie', 2015);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (61, 250, 'Piotr Kaczor', true, 'Niesamowite przygody', 2016);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (62, 230, 'Krzysztof Jankowski', true, 'Podróż w czasie', 2017);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (63, 234, 'Katarzyna Kowalska', true, 'Księga mocy', 2018);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (64, 274, 'Jan Wiśniewski', true, 'Odwaga i honor', 2011);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (65, 254, 'Monika Kaczmarek', true, 'Przygody w świecie fantasy', 2012);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (66, 278, 'Krystyna Nowakowski', true, 'Czas zemsty', 2013);
insert into public.book (id, amount_of_pages, author, available, title, publish_year) VALUES (4, 288, 'Krzysztof Wiśniewski', true, 'Świat w obiektywie', 2017);
insert into users (address, first_name, last_name, login, password)
values ('adres testowy1', 'kubus', 'puchatek', 'login1', 'password');
insert into users (address, first_name, last_name, login, password)
values ('adres testowy2', 'kubus2', 'puchatek3', 'login2', 'password');
insert into users (address, first_name, last_name, login, password)
values ('adres testowy3', 'kubus22', 'puchatek333', 'login3', 'password');
insert into users (address, first_name, last_name, login, password)
values ('adres testowy4', 'kubus333', 'puchatek33', 'login4', 'password');